name: Build C++ Game
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install SFML
      run: |
        vcpkg install sfml:x64-windows

    - name: Compile Game
      run: |
        g++ -c main.cpp -I"C:/vcpkg/packages/sfml_x64-windows/include"
        g++ main.o -o CountMaster.exe -L"C:/vcpkg/packages/sfml_x64-windows/lib" -lsfml-graphics -lsfml-window -lsfml-system

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Game-Build
        path: |
          *.exe
          C:/vcpkg/packages/sfml_x64-windows/bin/*.dll