name: Build Count Master PC
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Vcpkg & SFML
      shell: pwsh
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg install sfml:x64-windows

    - name: Compile Game
      shell: pwsh
      run: |
        $inc = "vcpkg/installed/x64-windows/include"
        $lib = "vcpkg/installed/x64-windows/lib"
        g++ -c main.cpp -I$inc
        g++ main.o -o CountMaster.exe -L$lib -lsfml-graphics -lsfml-window -lsfml-system

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: CountMaster-PC-Version
        path: |
          CountMaster.exe
          vcpkg/installed/x64-windows/bin/*.dll